build_env:
  stage: build
  script:
    - PREFIX=$(pwd)/env bash provision/70-python.sh &> env.log
  artifacts:
    paths:
      - env
      - env.log

run_tests:
  stage: test
  script:
    - PATH=$(pwd)/env/bin:$PATH COV=yes bash bin/run-tests.sh
