# http://conda.pydata.org/docs/travis.html
language: python
os:
  - linux
python:
  - "3.5"
install:
  - sudo apt-get update
  - sudo apt-get install -y libssl-dev
  - PREFIX=$(pwd)/env bash provision/70-python.sh
  - PATH=$(pwd)/env/bin:$PATH pip3 install coveralls
script:
  - PATH=$(pwd)/env/bin:$PATH COV=yes bash bin/run-tests.sh
after_success:
  - coveralls
