# http://conda.pydata.org/docs/travis.html
language: python

services:
  - docker

before_install:
  - docker build -t thevirtualbrain/tvb-recon:tests -f docker/Dockerfile-tests docker

script:
  - docker run -v $(pwd):/opt/tvb-recon --name tvb-recon thevirtualbrain/tvb-recon:tests /bin/bash -c "ls && source activate tvb-recon-tests && bash run-tests.sh"

after_script:
  - coveralls