# http://conda.pydata.org/docs/travis.html
language: python
os:
  - linux
install:
  - bash provision/05-ssl-dev.sh
  - PREFIX=$(pwd)/env bash provision/70-python.sh
  - PATH=$(pwd)/env/bin:$PATH pip3 install coveralls
script:
  - PATH=$(pwd)/env/bin:$PATH COV=yes bash run-tests.sh
after_success:
  - coveralls
